### ISSUE TITLE
About word alignment between Turkey and German Language Pair

### ISSUE THREAD

**Issue by vhientran** [Cosmos-Break/transfer-mt-submit#1]
Hi @Cosmos-Break ,
Thank you very much for your interesting paper with the provided source code: "Sub-Word Alignment is Still Useful: A Vest-Pocket Method for Enhancing Low-Resource Machine Translation".
I only wonder one point. In this paper, the author considers De->En as the parent language pair with large parallel bilingual dataset. For the child language pair as: Tr->En, I wonder how you can have bilingual dataset to train a word alignment model between De and Tr, using Eflomal as introduced in your paper.
Thank you!

**Comment by vhientran** [comment]
Hi @Cosmos-Break , Could you please help me answer the above question? Many thanks!

**Comment by Cosmos-Break** [comment]
Sorry for the late response, Eflomal doesn't need parallel corpus to train, It uses unsupervised method.

**Comment by vhientran** [comment]
Thanks for your reply. But I wonder if Eflomal doesn't need parallel corpus to train. I asked ChatGPT like that:
<img width="868" alt="Screen Shot 2023-03-06 at 21 10 21" src="https://user-images.githubusercontent.com/5416901/223107142-1f7ac216-02e2-4feb-b93e-c594e0d0534c.png">
Therefore, I wonder how we can obtain the parallel corpus (De<->Tr as example in your paper page 615) to train Eflomal. Thank you for your help!

**Comment by Cosmos-Break** [comment]
I use En-Tr parallel corpus to train eflomal.

**Comment by Cosmos-Break** [comment]
En and De have similar tokens, so word alignment between En-Tr can partially play a role as De-Tr alignment model.

**Comment by vhientran** [comment]
I got it. Thanks for your quick reply!
